### ISSUE TITLE
"Scaffold.of(context).showSnackBar" is deprecated 

### ISSUE THREAD

**Issue by Adityabhaumik** [cdli-gh/cdli-mobile-app#15]
"Scaffold.of(context).showSnackBar" is  depricated and a new way of doing this is made available (https://flutter.dev/docs/release/breaking-changes/scaffold-messenger)

**Comment by Adityabhaumik** [comment]
@NishealJ should I start working on this?

**Comment by Adityabhaumik** [comment]
@NishealJ I have made the "snackbar" changes and pushed but that not recognized as a different pr but went as a new commit in the previous loader pr  I made will that a problem?

**Comment by MrUnfunny** [comment]
Hi @Adityabhaumik
"Scaffold.of(context).showSnackBar" is not deprecated yet in the stable release. It's deprecated in beta and above versions. I believe you might be using them if you're shown this warning. Please check the timeline [here](https://flutter.dev/docs/release/breaking-changes/scaffold-messenger#timeline)

**Comment by Adityabhaumik** [comment]
@MrUnfunny shoot! didn't notice I have been using beta Thankss
