### ISSUE TITLE
Code Cleanup and change some part of code to follow Effective Dart guidelines

### ISSUE THREAD

**Issue by MrUnfunny** [cdli-gh/cdli-mobile-app#9]
Hello everyone,
While going through codebase, I noticed that it deviates from Effective Dart Guidelines as suggested by dart. 
For example- using snake_case instead of camelCase in some places, using lowerCamelCase instead of UpperCamelCase for naming classes etc.
There are also some unused imports. These leads to 30+ warnings in the codebase.
I'll be more than happy to create a pull request with these changes if required. 
@NishealJ Please let me know.

**Comment by NishealJ** [comment]
@MrUnfunny Yes, there are a lot of warnings.
It really required to lint the code and follow the rules.

Please feel free to create a PR, but this will require a lot of testing to make sure that you don't break an existing feature :)

**Comment by MrUnfunny** [comment]
> Please feel free to create a PR, but this will require a lot of testing to make sure that you don't break an existing feature :)
> 
Sure, I'll keep this in mind ;-)

**Comment by kanavpruthi** [comment]
Hey @NishealJ , please check this PR out, I've completed it since the issue was still open.

**Comment by NishealJ** [comment]
Hi @kanavpruthi there is already an open PR for this https://github.com/cdli-gh/cdli-mobile-app/pull/10

**Comment by kanavpruthi** [comment]
Hey @NishealJ, thanks for the reply. I thought that PR missed on something and hence wasn't merged. 
In this, I went a step beyond to remove all warnings apart from the dart guidelines for casing ( formatting, removing unused imports, and unused variables ). Kindly check. If you want any other changes to be made please do tell.( e.g. Refactoring )

**Comment by MrUnfunny** [comment]
Hey @kanavpruthi, #10 also includes removing imports, variables and formatting. The formatting caused large number of changes, maybe that's why it's taking time to review it.

**Comment by kanavpruthi** [comment]
Okay, no issues at all. Thanks for letting me know :)
